version: '3.9'

services:
  myapi:
    container_name: container-app
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - 5000:3000
    depends_on:
      - dbmongo
    links:
      - dbmongo
    volumes:
      - .:/usr/src/app
  dbmongo:
    container_name: container-mongodb
    image: mongo
    env_file:
      - .env
    ports:
      - 27018:27017
    logging:
      driver: none